sonar.projectKey=carlosdelcastillo_github_io_local
sonar.projectName=carlosdelcastillo.github.io

sonar.sources=src
sonar.tests=tests,src/test
sonar.sourceEncoding=UTF-8

sonar.typescript.tsconfigPath=tsconfig.sonar.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=dist/**,node_modules/**,.astro/**,src/test/**
sonar.cpd.exclusions=src/locales/**
